### ISSUE TITLE
How can i change the svg width.

### ISSUE THREAD

**Issue by medoer** [gera2ld/gatsby-remark-markmap#2]
I want to show the mindmap in the center of the page. and more wide. use gatsby netlify template.

![image](https://user-images.githubusercontent.com/20471718/84345156-2da3fd00-abdf-11ea-8c86-c25484e234ae.png)

**Comment by gera2ld** [comment]
For now you can add the following CSS to achieve this:

```css
.gatsby-markmap > svg {
  width: 100%;
  height: 300px; 
}
```

I'll see if this can be loaded by default in the future.
